List<Map<String, dynamic>> foodItems = [
  {'name': 'Spring Rolls', 'price': 150, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Chinese']},
  {'name': 'Chicken Tikka', 'price': 250, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Indian']},
  {'name': 'Pasta Alfredo', 'price': 300, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'name': 'Paneer Butter Masala', 'price': 200, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Fried Rice', 'price': 180, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'name': 'Caesar Salad', 'price': 120, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'name': 'Veg Manchurian', 'price': 190, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'name': 'Chicken Curry', 'price': 220, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Garlic Bread', 'price': 100, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'name': 'Shahi Paneer', 'price': 240, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Chow Mein', 'price': 150, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'name': 'Grilled Chicken', 'price': 350, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'name': 'Hakka Noodles', 'price': 160, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'name': 'Butter Chicken', 'price': 300, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Margherita Pizza', 'price': 250, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'name': 'Fish Curry', 'price': 270, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Tomato Soup', 'price': 90, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'name': 'Paneer Tikka', 'price': 200, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Indian']},
  {'name': 'Sweet Corn Soup', 'price': 100, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Chinese']},
  {'name': 'Lamb Chops', 'price': 400, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'name': 'Schezwan Fried Rice', 'price': 190, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'name': 'Rogan Josh', 'price': 280, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Chicken Satay', 'price': 220, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'name': 'Dal Makhani', 'price': 180, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Veg Biryani', 'price': 170, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Egg Curry', 'price': 200, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'name': 'Thai Green Curry', 'price': 320, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'name': 'Momos', 'price': 110, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Chinese']},
  {'name': 'Grilled Salmon', 'price': 450, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'name': 'Veg Hakka Noodles', 'price': 150, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
];
